# Generated by Django 4.1.4 on 2022-12-26 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "name",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("favourite", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Subreddit",
            fields=[
                (
                    "name",
                    models.CharField(max_length=21, primary_key=True, serialize=False),
                ),
                ("favourite", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=6,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Reddit post's ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=300, verbose_name="Title of a Reddit post"
                    ),
                ),
                (
                    "score",
                    models.IntegerField(
                        verbose_name="Number of upvotes on a reddit post"
                    ),
                ),
                ("url", models.URLField(verbose_name="Submission URL")),
                ("domain", models.CharField(max_length=50, verbose_name="Domain")),
                (
                    "created_utc",
                    models.DateTimeField(
                        verbose_name="Date the submission was created"
                    ),
                ),
                ("is_self", models.BooleanField(default=False)),
                ("is_video", models.BooleanField(default=False)),
                ("media_only", models.BooleanField(default=False)),
                ("media", models.JSONField(default=None)),
                ("media_embed", models.JSONField(default=None)),
                ("selftext", models.TextField(default=None, max_length=40000)),
                ("selftext_html", models.TextField(default=None)),
                ("nsfw", models.BooleanField(default=False)),
                ("thumbnail", models.URLField(verbose_name="Thumbnail URL")),
                ("secure_media", models.JSONField(default=None)),
                ("secure_media_embed", models.JSONField(default=None)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="reddit.author"
                    ),
                ),
                (
                    "subreddit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reddit.subreddit",
                    ),
                ),
            ],
        ),
    ]
