# Generated by Django 4.1.4 on 2022-12-24 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reddit", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="media_only",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="submission",
            name="is_self",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="submission",
            name="is_video",
            field=models.BooleanField(default=False),
        ),
    ]
