# Generated by Django 4.1.4 on 2022-12-26 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reddit", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="media",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="submission",
            name="media_embed",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="submission",
            name="secure_media",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="submission",
            name="secure_media_embed",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="submission",
            name="selftext",
            field=models.TextField(max_length=40000),
        ),
        migrations.AlterField(
            model_name="submission",
            name="selftext_html",
            field=models.TextField(),
        ),
    ]
