# Generated by Django 4.1.4 on 2022-12-26 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reddit", "0003_alter_submission_media_alter_submission_media_embed_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="selftext",
            field=models.TextField(default=str, max_length=40000),
        ),
        migrations.AlterField(
            model_name="submission",
            name="selftext_html",
            field=models.TextField(default=str),
        ),
    ]
