# Generated by Django 4.1.4 on 2022-12-30 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("reddit", "0004_alter_submission_selftext_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubmissionThumbnailImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="submissions/thumbs")),
                (
                    "image_ext",
                    models.CharField(
                        max_length=10, verbose_name="Image Extension E.G. jpg, png, gif"
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reddit.submission",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SubmissionFullImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="submissions/full")),
                (
                    "image_ext",
                    models.CharField(
                        max_length=10, verbose_name="Image Extension E.G. jpg, png, gif"
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reddit.submission",
                    ),
                ),
            ],
        ),
    ]
