# Generated by Django 4.1.4 on 2022-12-31 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reddit", "0005_submissionthumbnailimage_submissionfullimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="score",
            field=models.IntegerField(verbose_name="Upvotes"),
        ),
    ]
