# Generated by Django 4.1.4 on 2023-01-11 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reddit", "0007_alter_submission_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="submission",
            options={"get_latest_by": "created_utc", "ordering": ["-score"]},
        ),
    ]
