# Generated by Django 4.1.4 on 2023-01-31 10:50

from django.db import migrations, models


def make_permalink(apps, schema_editor):
    """
    Make permalink from fields of Submission
    """
    # Get historical Submission model from Reddit App
    Submission = apps.get_model("reddit", "Submission")
    for submission in Submission.objects.all():
        # Convert whitespace between words to underscore
        title = "_".join(str(submission.title).split())
        # Compose permalink from subreddit, id and title
        permalink = "https://www.reddit.com/r/%s/comments/%s/%s/" % (
            submission.subreddit.name,
            submission.id,
            title,
        )
        submission.permalink = permalink
        if len(submission.permalink) > 300:
            submission.permalink = "[invalid]"
        submission.save()


class Migration(migrations.Migration):

    dependencies = [
        ("reddit", "0008_alter_submission_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="permalink",
            field=models.URLField(
                default="", max_length=300, verbose_name="Permalink URL"
            ),
            preserve_default=False,
        ),
        migrations.RunPython(make_permalink),
    ]
